version: '3'

services:

  db:
    image: ghusta/postgres-world-db:2.3
    environment:
      POSTGRES_DATABASE: world-db
      POSTGRES_USER: world
      POSTGRES_PASSWORD: world123
    ports:
      - 5432:5432
      
  web:
    build: .
    depends_on: 
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_USER: world
      DATABASE_PASSWORD: world
      DATABASE_NAME: world-db
      DATABASE_PORT: 5432
      